
name: Node.js CI

on: 
  push:
   branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
       matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
       node-version: ${{ matrix.node-version }}
       
    - name: Install dependencies
      run: npm i
      
    - name: Building of the package
      run: npm run build
      
    - name: Publish to npm
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
