
name: Node.js CI

on: 
  push:
   branches:
    - main

permissions:
   contents: write
   issues: write
   pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
       matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
       node-version: ${{ matrix.node-version }}
       
    - run: npm ci
    - run: npm run build
    - run : npm audit signatures
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm run semantic-release
